/* Generated by scripts/proto2module from sensor.proto — do not edit. */
#include <pb_encode.h>
#include <pb_decode.h>
#include "sensor.pb.h"

/* Decode a protobuf buffer into a caller-provided SensorReading struct.
 * Returns 1 on success, 0 on failure. */
int sensor_parse(const unsigned char *in, size_t in_len, void *msg)
{
    pb_istream_t stream = pb_istream_from_buffer(in, in_len);
    return pb_decode(&stream, SensorReading_fields, msg) ? 1 : 0;
}

/* Encode a caller-provided SensorReading struct. *out_len is capacity on entry,
 * bytes written on success. Returns 1 on success, 0 on failure. */
int sensor_write(const void *msg, unsigned char *out, size_t *out_len)
{
    pb_ostream_t stream = pb_ostream_from_buffer(out, *out_len);
    int ok = pb_encode(&stream, SensorReading_fields, msg) ? 1 : 0;
    *out_len = (size_t)stream.bytes_written;
    return ok;
}
