/* Generated by scripts/proto2module from sensor.proto — host-side ABI.
 * Link the nanopb runtime (pb_common.c, pb_encode.c, pb_decode.c) into the
 * host firmware and resolve these names in udynlink_external_resolve_symbol():
 *   pb_decode, pb_encode, pb_istream_from_buffer, pb_ostream_from_buffer
 * The struct type lives in sensor.pb.h; the module owns the field tables. */
#ifndef SENSOR_PROTO_API_H
#define SENSOR_PROTO_API_H

#include <stddef.h>
#include "sensor.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Decode in_len bytes at `in` into a SensorReading struct. Returns 1 on success. */
int sensor_parse(const unsigned char *in, size_t in_len, void *msg);

/* Encode `msg` into `out`; *out_len is capacity in, bytes written out. */
int sensor_write(const void *msg, unsigned char *out, size_t *out_len);

#ifdef __cplusplus
}
#endif

#endif /* SENSOR_PROTO_API_H */
