/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorReading {
    uint32_t id;
    int32_t temperature; /* milli-degrees C */
    uint32_t humidity; /* per-mille */
    char tag[16];
    pb_size_t samples_count;
    uint32_t samples[8];
} SensorReading;

typedef struct _Config { /* for the multi-message comparison */
    uint32_t sample_period_ms;
    bool log_enabled;
    char device_name[24];
} Config;

typedef struct _Status { /* for the multi-message comparison */
    uint32_t uptime_s;
    uint32_t errors;
    char last_error[32];
} Status;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorReading_init_default               {0, 0, 0, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Config_init_default                      {0, 0, ""}
#define Status_init_default                      {0, 0, ""}
#define SensorReading_init_zero                  {0, 0, 0, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Config_init_zero                         {0, 0, ""}
#define Status_init_zero                         {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define SensorReading_id_tag                     1
#define SensorReading_temperature_tag            2
#define SensorReading_humidity_tag               3
#define SensorReading_tag_tag                    4
#define SensorReading_samples_tag                5
#define Config_sample_period_ms_tag              1
#define Config_log_enabled_tag                   2
#define Config_device_name_tag                   3
#define Status_uptime_s_tag                      1
#define Status_errors_tag                        2
#define Status_last_error_tag                    3

/* Struct field encoding specification for nanopb */
#define SensorReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       2) \
X(a, STATIC,   SINGULAR, UINT32,   humidity,          3) \
X(a, STATIC,   SINGULAR, STRING,   tag,               4) \
X(a, STATIC,   REPEATED, UINT32,   samples,           5)
#define SensorReading_CALLBACK NULL
#define SensorReading_DEFAULT NULL

#define Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sample_period_ms,   1) \
X(a, STATIC,   SINGULAR, BOOL,     log_enabled,       2) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       3)
#define Config_CALLBACK NULL
#define Config_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          1) \
X(a, STATIC,   SINGULAR, UINT32,   errors,            2) \
X(a, STATIC,   SINGULAR, STRING,   last_error,        3)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL

extern const pb_msgdesc_t SensorReading_msg;
extern const pb_msgdesc_t Config_msg;
extern const pb_msgdesc_t Status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorReading_fields &SensorReading_msg
#define Config_fields &Config_msg
#define Status_fields &Status_msg

/* Maximum encoded size of messages (where known) */
#define Config_size                              33
#define SENSOR_PB_H_MAX_SIZE                     SensorReading_size
#define SensorReading_size                       88
#define Status_size                              45

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
