# Protobuf module test: 1 struct == 1 module (see scripts/proto2module).
#
# The module exports parse()/write() for the SensorReading message; the
# message schema tables are compiled into the module, while the nanopb
# runtime (pb_common/pb_encode/pb_decode) is linked into the host firmware
# and exported through test_resolve_symbol() in test_qemu.c.
#
# sensor.pb.c/sensor.pb.h/sensor_mod.c are generated by
# `scripts/proto2module --struct SensorReading sensor.proto` and committed so
# this test does not need protoc installed.

test_data = {
    "desc": "Protobuf module: SensorReading parse/write round-trip",
    "modules": [["sensor_mod.c", "sensor.pb.c"]],
    "mkmodule_args": ("--public-symbols parse,write "
                      "--strip-non-public-syms "
                      "--build-flags=-I../../third_party/nanopb"),
    "required": [r"^protobuf round-trip OK \(\d+ bytes\)$"]
}
