# Protobuf module test: 1 struct == 1 module (see scripts/proto2module).
#
# The module exports sensor_parse()/sensor_write() for the SensorReading
# message (default export prefix = .proto basename); the message schema
# tables are compiled into the module, while the nanopb runtime
# (pb_common/pb_encode/pb_decode) is linked into the host firmware and
# exported through test_resolve_symbol() in test_qemu.c.
#
# sensor.pb.c/sensor.pb.h/sensor_mod.c are generated by
# `scripts/proto2module --struct SensorReading sensor.proto` (thunk exports
# on by default) and committed so this test does not need protoc installed.
# The module is loaded with the plain core loader, which leaves the thunk
# slots zeroed — direct parse/write calls are unaffected.

test_data = {
    "desc": "Protobuf module: SensorReading parse/write round-trip",
    "modules": [["sensor_mod.c", "sensor.pb.c"]],
    "mkmodule_args": ("--public-symbols sensor_parse,sensor_write,"
                      "udynlink_thunk_gateway,"
                      ".udynlink.thunk_export.sensor_parse,"
                      ".udynlink.thunk_export.sensor_write "
                      "--strip-non-public-syms "
                      "--build-flags=-I../../third_party/nanopb -I../../udynlink"),
    "required": [r"^protobuf round-trip OK \(\d+ bytes\)$"]
}
