; ModuleID = 'BitcodeBuffer'
source_filename = "test"
target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "thumbv7em-unknown-unknown-eabi"

@test.counter = internal unnamed_addr global i32 0, align 4

; Function Attrs: minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(none) uwtable
define dso_local i32 @hello(i32 %0) local_unnamed_addr #0 {
  %2 = add nsw i32 %0, 42
  ret i32 %2
}

; Function Attrs: minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(readwrite, argmem: none, inaccessiblemem: none) uwtable
define dso_local i32 @get_counter() local_unnamed_addr #1 {
  %1 = load i32, ptr @test.counter, align 4
  %2 = add nsw i32 %1, 1
  store i32 %2, ptr @test.counter, align 4
  ret i32 %2
}

; Function Attrs: minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(write, argmem: none, inaccessiblemem: none) uwtable
define dso_local void @set_counter(i32 %0) local_unnamed_addr #2 {
  store i32 %0, ptr @test.counter, align 4
  ret void
}

attributes #0 = { minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(none) uwtable "frame-pointer"="none" "target-cpu"="cortex-m4" "target-features"="+db,+dsp,+v4t,+v5t,+v5te,+v6,+v6k,+v6m,+v6t2,+v7,+v7clrex,+v8m,+hwdiv,+loop-align,+mclass,+no-branch-predictor,+noarm,+slowfpvfmx,+slowfpvmlx,+thumb2,+thumb-mode,+use-misched,+armv7e-m,-32bit,-8msecext,-aapcs-frame-chain,-aclass,-acquire-release,-aes,-atomics-32,-avoid-movs-shop,-avoid-partial-cpsr,-bf16,-big-endian-instructions,-cde,-cdecp0,-cdecp1,-cdecp2,-cdecp3,-cdecp4,-cdecp5,-cdecp6,-cdecp7,-cheap-predicable-cpsr,-clrbhb,-crc,-crypto,-d32,-dfb,-disable-postra-scheduler,-dont-widen-vmovs,-dotprod,-execute-only,-expand-fp-mlx,-fix-cmse-cve-2021-35465,-fix-cortex-a57-aes-1742098,-fp16,-fp16fml,-fp64,-fp-armv8,-fp-armv8d16,-fp-armv8d16sp,-fp-armv8sp,-fpao,-fpregs,-fpregs16,-fpregs64,-fullfp16,-fuse-aes,-fuse-literals,-harden-sls-blr,-harden-sls-nocomdat,-harden-sls-retbr,-v8,-v8.1a,-v8.1m.main,-v8.2a,-v8.3a,-v8.4a,-v8.5a,-v8.6a,-v8.7a,-v8.8a,-v8.9a,-v8m.main,-v9.1a,-v9.2a,-v9.3a,-v9.4a,-v9.5a,-v9a,-hwdiv-arm,-i8mm,-iwmmxt,-iwmmxt2,-lob,-long-calls,-mp,-muxed-units,-mve,-mve1beat,-mve2beat,-mve4beat,-mve.fp,-nacl-trap,-neon,-neon-fpmovs,-neonfp,-no-bti-at-return-twice,-no-movt,-no-neg-immediates,-nonpipelined-vfp,-pacbti,-perfmon,-prefer-ishst,-prefer-vmovsr,-prof-unpr,-ras,-rclass,-read-tp-tpidrprw,-read-tp-tpidruro,-read-tp-tpidrurw,-reserve-r9,-ret-addr-stack,-sb,-sha2,-slow-fp-brcc,-slow-load-D-subreg,-slow-odd-reg,-slow-vdup32,-slow-vgetlni32,-soft-float,-splat-vfp-neon,-strict-align,-trustzone,-use-mipipeliner,-armv4,-armv4t,-armv5t,-armv5te,-armv5tej,-armv6,-armv6j,-armv6k,-armv6kz,-armv6-m,-armv6s-m,-armv6t2,-armv7-a,-armv7-m,-armv7-r,-armv7ve,-armv8.1-a,-armv8.1-m.main,-armv8.2-a,-armv8.3-a,-armv8.4-a,-armv8.5-a,-armv8.6-a,-armv8.7-a,-armv8.8-a,-armv8.9-a,-armv8-a,-armv8-m.base,-armv8-m.main,-armv8-r,-armv9.1-a,-armv9.2-a,-armv9.3-a,-armv9.4-a,-armv9.5-a,-armv9-a,-vfp2,-vfp2sp,-vfp3,-vfp3d16,-vfp3d16sp,-vfp3sp,-vfp4,-vfp4d16,-vfp4d16sp,-vfp4sp,-virtualization,-vldn-align,-vmlx-forwarding,-vmlx-hazards,-wide-stride-vfp,-xscale,-zcz" "use-soft-float"="true" }
attributes #1 = { minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(readwrite, argmem: none, inaccessiblemem: none) uwtable "frame-pointer"="none" "target-cpu"="cortex-m4" "target-features"="+db,+dsp,+v4t,+v5t,+v5te,+v6,+v6k,+v6m,+v6t2,+v7,+v7clrex,+v8m,+hwdiv,+loop-align,+mclass,+no-branch-predictor,+noarm,+slowfpvfmx,+slowfpvmlx,+thumb2,+thumb-mode,+use-misched,+armv7e-m,-32bit,-8msecext,-aapcs-frame-chain,-aclass,-acquire-release,-aes,-atomics-32,-avoid-movs-shop,-avoid-partial-cpsr,-bf16,-big-endian-instructions,-cde,-cdecp0,-cdecp1,-cdecp2,-cdecp3,-cdecp4,-cdecp5,-cdecp6,-cdecp7,-cheap-predicable-cpsr,-clrbhb,-crc,-crypto,-d32,-dfb,-disable-postra-scheduler,-dont-widen-vmovs,-dotprod,-execute-only,-expand-fp-mlx,-fix-cmse-cve-2021-35465,-fix-cortex-a57-aes-1742098,-fp16,-fp16fml,-fp64,-fp-armv8,-fp-armv8d16,-fp-armv8d16sp,-fp-armv8sp,-fpao,-fpregs,-fpregs16,-fpregs64,-fullfp16,-fuse-aes,-fuse-literals,-harden-sls-blr,-harden-sls-nocomdat,-harden-sls-retbr,-v8,-v8.1a,-v8.1m.main,-v8.2a,-v8.3a,-v8.4a,-v8.5a,-v8.6a,-v8.7a,-v8.8a,-v8.9a,-v8m.main,-v9.1a,-v9.2a,-v9.3a,-v9.4a,-v9.5a,-v9a,-hwdiv-arm,-i8mm,-iwmmxt,-iwmmxt2,-lob,-long-calls,-mp,-muxed-units,-mve,-mve1beat,-mve2beat,-mve4beat,-mve.fp,-nacl-trap,-neon,-neon-fpmovs,-neonfp,-no-bti-at-return-twice,-no-movt,-no-neg-immediates,-nonpipelined-vfp,-pacbti,-perfmon,-prefer-ishst,-prefer-vmovsr,-prof-unpr,-ras,-rclass,-read-tp-tpidrprw,-read-tp-tpidruro,-read-tp-tpidrurw,-reserve-r9,-ret-addr-stack,-sb,-sha2,-slow-fp-brcc,-slow-load-D-subreg,-slow-odd-reg,-slow-vdup32,-slow-vgetlni32,-soft-float,-splat-vfp-neon,-strict-align,-trustzone,-use-mipipeliner,-armv4,-armv4t,-armv5t,-armv5te,-armv5tej,-armv6,-armv6j,-armv6k,-armv6kz,-armv6-m,-armv6s-m,-armv6t2,-armv7-a,-armv7-m,-armv7-r,-armv7ve,-armv8.1-a,-armv8.1-m.main,-armv8.2-a,-armv8.3-a,-armv8.4-a,-armv8.5-a,-armv8.6-a,-armv8.7-a,-armv8.8-a,-armv8.9-a,-armv8-a,-armv8-m.base,-armv8-m.main,-armv8-r,-armv9.1-a,-armv9.2-a,-armv9.3-a,-armv9.4-a,-armv9.5-a,-armv9-a,-vfp2,-vfp2sp,-vfp3,-vfp3d16,-vfp3d16sp,-vfp3sp,-vfp4,-vfp4d16,-vfp4d16sp,-vfp4sp,-virtualization,-vldn-align,-vmlx-forwarding,-vmlx-hazards,-wide-stride-vfp,-xscale,-zcz" "use-soft-float"="true" }
attributes #2 = { minsize mustprogress nofree noimplicitfloat norecurse noredzone nosanitize_coverage nosync nounwind optsize skipprofile willreturn memory(write, argmem: none, inaccessiblemem: none) uwtable "frame-pointer"="none" "target-cpu"="cortex-m4" "target-features"="+db,+dsp,+v4t,+v5t,+v5te,+v6,+v6k,+v6m,+v6t2,+v7,+v7clrex,+v8m,+hwdiv,+loop-align,+mclass,+no-branch-predictor,+noarm,+slowfpvfmx,+slowfpvmlx,+thumb2,+thumb-mode,+use-misched,+armv7e-m,-32bit,-8msecext,-aapcs-frame-chain,-aclass,-acquire-release,-aes,-atomics-32,-avoid-movs-shop,-avoid-partial-cpsr,-bf16,-big-endian-instructions,-cde,-cdecp0,-cdecp1,-cdecp2,-cdecp3,-cdecp4,-cdecp5,-cdecp6,-cdecp7,-cheap-predicable-cpsr,-clrbhb,-crc,-crypto,-d32,-dfb,-disable-postra-scheduler,-dont-widen-vmovs,-dotprod,-execute-only,-expand-fp-mlx,-fix-cmse-cve-2021-35465,-fix-cortex-a57-aes-1742098,-fp16,-fp16fml,-fp64,-fp-armv8,-fp-armv8d16,-fp-armv8d16sp,-fp-armv8sp,-fpao,-fpregs,-fpregs16,-fpregs64,-fullfp16,-fuse-aes,-fuse-literals,-harden-sls-blr,-harden-sls-nocomdat,-harden-sls-retbr,-v8,-v8.1a,-v8.1m.main,-v8.2a,-v8.3a,-v8.4a,-v8.5a,-v8.6a,-v8.7a,-v8.8a,-v8.9a,-v8m.main,-v9.1a,-v9.2a,-v9.3a,-v9.4a,-v9.5a,-v9a,-hwdiv-arm,-i8mm,-iwmmxt,-iwmmxt2,-lob,-long-calls,-mp,-muxed-units,-mve,-mve1beat,-mve2beat,-mve4beat,-mve.fp,-nacl-trap,-neon,-neon-fpmovs,-neonfp,-no-bti-at-return-twice,-no-movt,-no-neg-immediates,-nonpipelined-vfp,-pacbti,-perfmon,-prefer-ishst,-prefer-vmovsr,-prof-unpr,-ras,-rclass,-read-tp-tpidrprw,-read-tp-tpidruro,-read-tp-tpidrurw,-reserve-r9,-ret-addr-stack,-sb,-sha2,-slow-fp-brcc,-slow-load-D-subreg,-slow-odd-reg,-slow-vdup32,-slow-vgetlni32,-soft-float,-splat-vfp-neon,-strict-align,-trustzone,-use-mipipeliner,-armv4,-armv4t,-armv5t,-armv5te,-armv5tej,-armv6,-armv6j,-armv6k,-armv6kz,-armv6-m,-armv6s-m,-armv6t2,-armv7-a,-armv7-m,-armv7-r,-armv7ve,-armv8.1-a,-armv8.1-m.main,-armv8.2-a,-armv8.3-a,-armv8.4-a,-armv8.5-a,-armv8.6-a,-armv8.7-a,-armv8.8-a,-armv8.9-a,-armv8-a,-armv8-m.base,-armv8-m.main,-armv8-r,-armv9.1-a,-armv9.2-a,-armv9.3-a,-armv9.4-a,-armv9.5-a,-armv9-a,-vfp2,-vfp2sp,-vfp3,-vfp3d16,-vfp3d16sp,-vfp3sp,-vfp4,-vfp4d16,-vfp4d16sp,-vfp4sp,-virtualization,-vldn-align,-vmlx-forwarding,-vmlx-hazards,-wide-stride-vfp,-xscale,-zcz" "use-soft-float"="true" }

!llvm.module.flags = !{!0}

!0 = !{i32 8, !"PIC Level", i32 2}
