/* Generated by scripts/sm2module from door.json — do not edit. */
#include <stdint.h>
#include <stddef.h>
#include "door_contract.h"

#define DOOR_N_STATES  (3u)
#define DOOR_N_EVENTS  (3u)

/* transition matrix [state][event]; 0xFF = no transition */
static const uint8_t door_trans[3][3] = {
    {/* closed */ 0x01, 0xFF, 0xFF},
    {/* open */ 0xFF, 0x02, 0xFF},
    {/* locked */ 0xFF, 0xFF, 0x01}
};
/* name blob: NUL-separated state names, then event names */
static const char door_name_blob[] =
    "closed\0open\0locked\0push\0lock\0unlock\0";

/* offsets into the name blob: [0..3) states, then events */
static const uint16_t door_name_offs[6] = {
    0u, 7u, 12u, 19u, 24u, 29u
};


uint8_t door_step(uint8_t state, uint8_t event, void *ctx)
{
    uint8_t next;
    if (state >= DOOR_N_STATES || event >= DOOR_N_EVENTS)
        return state;
    next = door_trans[state][event];
    if (next == 255u || next == state)
        return state;
    switch (state * 3u + event) {
    case 4u: door_action_lock(ctx); break;
    case 8u: door_action_unlock(ctx); break;
    }
    return next;
}

const char *door_state_name(uint8_t state)
{
    return state < DOOR_N_STATES
               ? door_name_blob + door_name_offs[state] : 0;
}

const char *door_event_name(uint8_t event)
{
    return event < DOOR_N_EVENTS
               ? door_name_blob + door_name_offs[DOOR_N_STATES + event]
               : 0;
}

uint8_t door_event_id(const char *name)
{
    uint8_t i;
    if (!name)
        return 255u;
    for (i = 0; i < DOOR_N_EVENTS; i++) {
        const char *a = door_name_blob
                        + door_name_offs[DOOR_N_STATES + i];
        const char *b = name;
        while (*a && *a == *b) { a++; b++; }
        if (*a == *b)
            return i;
    }
    return 255u;
}
