/* Generated by scripts/sm2module from door.json — host-side contract.
 * The host implements the action hooks below and resolves
 * them by name in udynlink_external_resolve_symbol().
 * The transition tables live in the module; this header is the shared ABI. */
#ifndef DOOR_CONTRACT_H
#define DOOR_CONTRACT_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* states */
#define DOOR_STATE_CLOSED 0u
#define DOOR_STATE_OPEN 1u
#define DOOR_STATE_LOCKED 2u

/* events */
#define DOOR_EVENT_PUSH 0u
#define DOOR_EVENT_LOCK 1u
#define DOOR_EVENT_UNLOCK 2u

/* Process `event` in `state`; returns the next state (unchanged when the
 * event has no transition). `ctx` is forwarded to actions uninterpreted. */
uint8_t door_step(uint8_t state, uint8_t event, void *ctx);

/* names (NULL when out of range); event_id maps a name back to its id
 * (255u when unknown) */
const char *door_state_name(uint8_t state);
const char *door_event_name(uint8_t event);
uint8_t door_event_id(const char *name);
/* action hook: implement in the host firmware and resolve by name in
 * udynlink_external_resolve_symbol() ("<pfx>_action_<name>") */
void door_action_lock(void *ctx);

/* action hook: implement in the host firmware and resolve by name in
 * udynlink_external_resolve_symbol() ("<pfx>_action_<name>") */
void door_action_unlock(void *ctx);

#ifdef __cplusplus
}
#endif

#endif /* DOOR_CONTRACT_H */
