# State-chart module test: the chart compiles to a self-contained module plus
# two host-side action hooks (see scripts/sm2module). The module exports
# door_step()/door_state_name()/door_event_name()/door_event_id(); the host
# implements door_action_lock()/door_action_unlock() and resolves them in
# test_resolve_symbol() in test_qemu.c.
#
# door_mod.c and door_contract.h are generated by
# `scripts/sm2module tests/test-statechart-module/door.json --gen-c-header`
# and committed so this test does not need any codegen tooling.

test_data = {
    "desc": "State-chart module: door step() transitions with host actions",
    "modules": [["door_mod.c"]],
    "mkmodule_args": ("--public-symbols door_step,door_state_name,"
                      "door_event_name,door_event_id "
                      "--strip-non-public-syms"),
    "required": [r"^statechart round-trip OK \(2 actions\)$"]
}
